services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: justoni
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5332/jwaltercreative
      SPRING_DATASOURCE_USERNAME: justoni
      SPRING_DATASOURCE_PASSWORD: supersecretpassword

networks:
  db:
    driver: bridge

volumes:
  db: